baseURL = "https://vfcardoso.dev/"
languageCode = "en-us"
title = "Vinícius Cardoso - Blog pessoal"
theme = "archie"

# copyright = "© Vinícius Cardoso"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate = 3 # articles per page

[params]
	mode = "toggle" # color-mode → light,dark,toggle or auto
	useCDN = false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Uma pequena coleção de ideias. Textos de minha autoria."
	favicon = "favicon.ico"

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/vfcardoso-dev"

[[params.social]]
name = "Mastodon"
icon = "mastodon"
url = "https://bolha.us/vfcardoso"

# Main menu Items

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "Sobre"
url = "/about"
weight = 4